### ISSUE TITLE
Использование mustache-express

### ISSUE THREAD

**Issue by armleo** [gonzazoid/openhabr#5]
Рекомендую использовать [mustache-express](https://www.npmjs.com/package/mustache-express) для темплейтов. Так же разделить Partials и Templates (например темплейты .mustache а partials .tpl итд итп)

**Comment by pomeo** [comment]
Так он и используется

**Comment by armleo** [comment]
Имелось ввиду его добавить в package.json он ведь в mustache по умолочению не включен. (или я че то путаю?)

**Comment by pomeo** [comment]
Я к тому, что какой смысл этих телодвижений, если mustache уже используется

**Comment by armleo** [comment]
Ну как хотите. Только я не думаю что consolidate лучшее решение. Хоть он и использует под собой mustache-express. тем более оно тянет ОЧЕНЬ МНОГО зависимостей (относительно одного mustache-express). Флаг вам в руки как хотите так и делайте! Всеравно круто получится :+1:

**Comment by pomeo** [comment]
Он под собой использует https://github.com/janl/mustache.js так же как и mustache-express.
Я же не против, это диалог, вот я и интересуюсь, в чём смысл менять одно на другое кроме количества папок в node_modules?

**Comment by armleo** [comment]
Ничего другого кроме личных предпочтений :)
А юнит тестирование и JSDoc будет?

**Comment by pomeo** [comment]
Это не ко мне, коммитить сюда я уже больше не смогу, времени нет. Зашёл случайно, глянуть какое здесь движение.
